In [ ]:
from lrTotalClose import lnFit

# To access from another folder
import sys
import os
sys.path.append(os.path.abspath("../Data Cleaning"))
from Plotting import lnPlot, plotLineFit

lnPlot('..//Data/Log_Simple_Returns.csv', 'Log-Data')

plotLineFit('..//Data/Simple_Returns.csv', 'Simple Returns')

    Year-Month  Close(Average)  Avg Monthly Returns  Log-Data
0      2016-03       23.989134                  NaN  3.177601
1      2016-04       24.174308             0.771909  3.185290
2      2016-05       21.622307           -10.556667  3.073726
3      2016-06       22.016291             1.822119  3.091783
4      2016-07       22.457024             2.001846  3.111603
..         ...             ...                  ...       ...
116    2025-11      271.333742             5.248139  5.603350
117    2025-12      276.048058             1.737460  5.620575
118    2026-01      257.408636            -6.752238  5.550665
119    2026-02      269.111013             4.546225  5.595124
120    2026-03      261.349997            -2.883946  5.565860

[121 rows x 4 columns]

In [1]:
from lrTotalClose import modelQuality
modelQuality('..//Data/Log_Simple_Returns.csv', 'Log-Data')

,Distribution,AIC,BIC,Params
3,johnsonsu,5832.554561,5855.871491,"(-5.847853450009545, 1221.5754722809506, 0, 94..."
4,genhyperbolic,11095.446846,11124.593009,"(1.7514994398963126, 0.5776935582656911, 0.577..."
0,norm,14787.671631,14799.330096,"(0, 4.583671483753172)"
1,t,14789.671631,14807.159329,"(42915147131314.08, 0, 4.583671366389826)"
5,hypsecant,15438.683259,15450.341724,"(0, 3.7680414793226986)"
2,laplace,16093.717186,16105.375651,"(0, 4.5183618871537705)"